### ISSUE TITLE
VSCode notebook support

### ISSUE THREAD

**Issue by fekad** [fekad/jupyter-jsmol#15]
Vscode uses its own interface to communicate with the iPython kernels. 
Because the jupyter-jsmol package builds the JS library "locally", currently it is not usable in VSCode.

**Comment by fekad** [comment]
Big changes are coming soon for the interface between jupyter notebook and VsCode:
https://towardsdatascience.com/vscode-jupyter-notebooks-are-getting-an-upgrade-cc9aaaefc744

It would make sense to wait until there will be a more-or-less stable interface and integrate `jupyter-jsmol` widget into that one...

**Comment by fekad** [comment]
using jsmol in vscode is not a requested feature so I close this issue for now.

**Comment by gmrigna** [comment]
Any progress on this by any chance? Thanks for this effort @fekad

**Comment by fekad** [comment]
@gmrigna As far as I know it is quite hard to solve this. 
The main issue is that vscode only uses JS codes that are accessible directly from the internet so it doesn't allow you to use the local version of the code. So jsmol needs to be published first as a proper package then we have to publish the widget itself. Right now all this code is embedded locally into python package.
Unfortunately, the JS version of Jmol is not priority of the J(s)mol team so it will not happen soon.
All in all, I'm not an expert in JS so it would be nice to find someone how is really know how this is work...
