### ISSUE TITLE
from_file(inline=True) very slow

### ISSUE THREAD

**Issue by markperri** [fekad/jupyter-jsmol#17]
JsmolView is very slow when loading from a file (takes about a minute)
`view1 = JsmolView.from_file("molecule.molden") `

When using inline=False it only takes a couple seconds to load
`view1 = JsmolView.from_file("molecule.molden",inline=False) `

Would you consider changing the default to inline=False?  JSmol seems to be faster at reading files than Python.

**Comment by fekad** [comment]
Thank you for the suggestion. Directly loading from files works perfectly when you are using your local machine, but security reasons it is forbidden for jupyterhub deployments when the path is an absolute path. This was the main reason to chose `inline=True` as the default.

I completely agree that the performance difference is huge so it makes sense to use `inline=False`  for the default value.

**Comment by fekad** [comment]
@markperri  Please have a look the new PR to change the default value and if you ok for you I can merge into the master. Thanks again for the suggestion.

**Comment by fekad** [comment]
Implemented in #19
