### ISSUE TITLE
Correct spacegroup information for pymatgen structures

### ISSUE THREAD

**Issue by fekad** [fekad/jupyter-jsmol#20]
The `quickview` method converts the structure into cif format and pass it to the jsmol.
Pymatgen uses P 1 by default and only analyse the spacegroup when the `symprec` parameter has been passed to the `CifWriter`.
https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/cif.py#L1296

We could use eg. `symprec=0.1` as the default value to show the "correct" spacegroup information in the viewer.

**Comment by gpetretto** [comment]
0.1 seems a bit large.  I think that a default of 0.01 (or even 0.001) should be fine.  
It could make sense to have it as an optional argument in the `quickview`. In that case it might be good to also have the `angle_tolerance`. These values could also be passed to the `SpaceGroupAnalyzer` when you convert to the conventional structure.

**Comment by fekad** [comment]
implemented in #21
