### ISSUE TITLE
Notebook 6.4.3:  Uncaught TypeError: Cannot read property 'println' of undefined     at l (JSmol.min.nojq.js:89)

### ISSUE THREAD

**Issue by markperri** [fekad/jupyter-jsmol#32]
I just upgraded notebook to 6.4.3 and jupyter-jsmol to 2021.3.0.  When I try to display JSmol, I get this error in the JS console:

`Uncaught TypeError: Cannot read property 'println' of undefined
    at l (JSmol.min.nojq.js:89)`

I'm not sure what broke, this worked well last year in an older notebook.  I even tried downgrading jupyter-jsmol to an earlier version, but I get the same error.  The line with the error is:

` self.System && System.out.println(f);`

There's some JS error causing System.out to not be defined, but I have no idea what could be causing this.  Any ideas?

**Comment by markperri** [comment]
It looks like there is a clash with the global System class being defined by both JSmol and React.  If you replace System with Zystem in all the files in the jsmol directory then it works fine.

**Comment by fekad** [comment]
Hi @markperri! Thanks for all the information. I have to finish something else but I will try to update the package at the end of this week. There are also some automatic suggestions from github to improve the security of the package.

**Comment by fekad** [comment]
Thanks again @markperri! I'm not an expert in JS so I'm grateful for your suggestion :)
