### ISSUE TITLE
launch Binder fails

### ISSUE THREAD

**Issue by fomightez** [fekad/jupyter-jsmol#33]
Currently clicking on the `launch Binder` badge fails as an image to run cannot be built.

Seeing:

```
Failed to build jupyter-jsmol
ERROR: Could not build wheels for jupyter-jsmol which use PEP 517 and cannot be installed directly
Removing intermediate container 3a90e58c2319
The command '/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir .' returned a non-zero code: 1
```

I don't know if this is an easy fix at present.  
I do know from testing that a work-around option until it is an easy fix, would be to point the `launch binder` URL at another repo or gist where [configuration files](https://mybinder.readthedocs.io/en/latest/using/config_files.html) (most likely `requirements.txt` or `environment.yml`)  are used to install it via pip, because sessions launched from https://github.com/binder-examples/python-conda_pip where I clone in the content from this repo, and run in `%pip install jupyter_jsmol` at the top of the example notebooks allows them to work.  
I have such an example gist [here](https://gist.github.com/fomightez/c6c0954414a8e576c5c2611c64163790). 
Launch that works and opens the first example notebook:
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gist/fomightez/c6c0954414a8e576c5c2611c64163790/HEAD?filepath=1%20-%20Basic%20usage.ipynb)

**Comment by fekad** [comment]
Thanks, for this @fomightez! In the end I used a slightly different solution that you suggested. Let's hope it works :)

**Comment by fekad** [comment]
it was too early to close it.

**Comment by ltalirz** [comment]
I guess this particular issue can be closed - at least for me, binder launches correctly.

**Comment by ltalirz** [comment]
correct, the widget currently does not work but this is a different problem tracked in https://github.com/fekad/jupyter-jsmol/issues/37

**Comment by fekad** [comment]
@fomightez Sorry for the long delay but now it should work. 🤞 
Right now, [MyBinder uses the master branch](https://mybinder.org/v2/gh/fekad/jupyter-jsmol/master?filepath=examples) of the package but for creating a release there are still a few things that need to be sorted.

**Comment by fomightez** [comment]
Seems to be working in both the classic notebook and JupyterLab now. Awesome. I'm not in any rush and so feel free to work at your own pace though. I think I just saw the September updates really late and was checking it out and sharing what I noted.

**Comment by fekad** [comment]
I'm closing this issue now but please feel free to reopen anytime needed.
