### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jamesjer** [fekad/jupyter-jsmol#36]
In setup.py, a claim is made that this project is released under the BSD license.  There are many flavors of the BSD license, but most of them have clauses that read something like this:

> * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

That cannot be done with this project, because no copyright notice or list of conditions has been provided.  Would you please add a COPYING or LICENSE file containing the exact license terms?

In any case, the project cannot be covered by just the BSD license, because it contains files with MIT license declarations (such as `jupyter_jsmol/nbextension/jsmol/js/JSmol.full.js`), files with dual MIT/LGPL3 license declarations (such as `jupyter_jsmol/nbextension/jsmol/js/JSmol.GLmol.full.js`), and files with dual MIT/GPL license declarations (such as `jupyter_jsmol/nbextension/jsmol/js/JSmoljQueryExt.js`).  It would be good to know the full list of licenses that cover the files of this project.

**Comment by jamesjer** [comment]
It looks like the exceptions to BSD are:

- jupyter_jsmol/nbextension/jsmol/j2s/J/export/_X3dExporter.js: LGPL (unspecified version)
- jupyter_jsmol/nbextension/jsmol/j2s/_WASM/wasi.esm.js: Apache License 2.0
- jupyter_jsmol/nbextension/jsmol/j2s/java/lang/ClassExt.js: Eclipse Public License 1.0
- jupyter_jsmol/nbextension/jsmol/js/JSmol.GLmol.full.js: MIT or LGPL version 3
- jupyter_jsmol/nbextension/jsmol/js/JSmol.full.js: part MIT and part MIT or GPL (unspecified version)
- jupyter_jsmol/nbextension/jsmol/js/JSmol.full.lite.js: MIT
- jupyter_jsmol/nbextension/jsmol/js/JSmol.full.lite.nojq.js: MIT or GPL (unspecified version)
- jupyter_jsmol/nbextension/jsmol/js/JSmol.full.nojq.js: MIT or GPL (unspecified version)
- jupyter_jsmol/nbextension/jsmol/js/JSmolGLmol.js: MIT or LGPL version 3
- jupyter_jsmol/nbextension/jsmol/js/JSmoljQueryExt.js: MIT or GPL (unspecified version)

**Comment by fekad** [comment]
I'm trying to figure out the proper license for this project. Although it is not explicitly stated but the minimised version of JS files should be served under the same license as its "full" version. 
As an extra complication, I had to modify the content of a lot of these files because there is a variable conflict that will not be resolved by the original developers. (more here: https://sourceforge.net/p/jmol/patches/38/).
From my side, I'm also happy to ease on the license of my code...

**Comment by fekad** [comment]
@jamesjer Before releasing the next version I want to make licensing right. 
- I moved out the jsmol dependency into its own folder (/jsmol) which contains its own original license file.
- For the rest of the code I switched to mit license to avoid making life simpler.
- Using Jsmol in this package has been mentioned in the main license file as well.

**Comment by fekad** [comment]
The last release contains all the modifications related to clarification of the Licenses. 
Please feel free to reopen this issue if needed
