### ISSUE TITLE
Superimposition of structures

### ISSUE THREAD

**Issue by ColineUVSQ** [fekad/jupyter-jsmol#39]

**Comment by ColineUVSQ** [comment]
Hi everyone ! 
Is it possible to load several structures in the same Jsmol view with jupyter_jsmol ?

**Comment by fekad** [comment]
Yes it is possible but there are multiple ways:
- JSmol way:
   you can create a viewer
  ```
  view1 = JsmolView() # pythonic way but it might be slower
  display(view1)
  ```
   and use JSmol's scripting capabilities (https://chemapps.stolaf.edu/jmol/docs/#loadappend)
   ```
   view1.script("load /files/data/c2h410.xyz")
   view1.script("load APPEND /files/data/coord.xyz; frame *")
   ```
- Pythonic way: use a package (like `ase` or `pymatgen`) to construct the superimposed structure and use JsmolView only as a viewer

**Comment by ColineUVSQ** [comment]
Thank you for your response ! It is working for me
